from django.urls import path

from .views import (
    CollectionListView,
    CollectionPostsView,
    PostListCreateView,
    batch_events,
    create_comment,
    create_story,
    feed,
    home_feed,
    semantic_feed,
    follow_user,
    get_chat_room,
    get_heatmap,
    get_or_create_dm,
    list_chat_rooms,
    list_comments,
    list_messages,
    list_notifications,
    mark_notifications_read,
    mark_room_read,
    move_saved_post,
    post_detail,
    save_post,
    search_users,
    send_message,
    stories_feed,
    toggle_like,
    upload_media,
    user_posts,
    user_profile,
    view_story,
)

urlpatterns = [
    path("posts/", PostListCreateView.as_view(), name="posts"),
    path("feed/", feed, name="feed"),
    path("feed/home/", home_feed, name="home-feed"),
    path("feed/semantic/", semantic_feed, name="semantic-feed"),
    path("upload/", upload_media, name="upload"),
    path("posts/<int:post_id>/", post_detail, name="post-detail"),
    path("posts/<int:post_id>/like/", toggle_like, name="toggle-like"),
    path("posts/<int:post_id>/comments/", list_comments, name="list-comments"),
    path("posts/<int:post_id>/comment/", create_comment, name="create-comment"),
    path("users/search/", search_users, name="search-users"),
    path("users/<int:user_id>/follow/", follow_user, name="follow-user"),
    path("users/<str:username>/posts/", user_posts, name="user-posts"),
    path("users/<str:username>/", user_profile, name="user-profile"),
    path("stories/", create_story, name="create-story"),
    path("stories/feed/", stories_feed, name="stories-feed"),
    path("stories/<int:story_id>/view/", view_story, name="view-story"),
    path("posts/<int:post_id>/save/", save_post, name="save-post"),
    path("collections/", CollectionListView.as_view(), name="collections"),
    path("collections/<int:collection_id>/posts/", CollectionPostsView.as_view(), name="collection-posts"),
    path("saved/<int:saved_id>/move/", move_saved_post, name="move-saved"),
    path("analytics/batch-events/", batch_events, name="batch-events"),
    path("analytics/posts/<int:post_id>/heatmap/", get_heatmap, name="get-heatmap"),
    path("chat/rooms/", list_chat_rooms, name="chat-rooms"),
    path("chat/dm/", get_or_create_dm, name="chat-dm"),
    path("chat/rooms/<int:room_id>/", get_chat_room, name="chat-room-detail"),
    path("chat/rooms/<int:room_id>/messages/", list_messages, name="chat-messages"),
    path("chat/rooms/<int:room_id>/read/", mark_room_read, name="chat-room-read"),
    path("chat/rooms/<int:room_id>/send/", send_message, name="chat-send"),
    path("notifications/", list_notifications, name="notifications"),
    path("notifications/read/", mark_notifications_read, name="notifications-read"),
]
